### ISSUE TITLE
DeepSEA model doesn't support variant effect prediction

### ISSUE THREAD

**Issue by TzuTingWei** [kipoi/models#280]
I recently re-ran my code for extracting SNV effect using kipoi-veff score_variants() function in DeepSEA model. 

However, an error popped up "Exception: Model deosn't support variant effect prediction according model yaml file."

I found it could be coming from this git history: Removing postprocessing 2ca080d 13 days ago

Is it still possible to have the score_variants() function with the scores of ref, alt, diff, and deepsea_effect? 

It is very urgent. Thank you!

**Comment by haimasree** [comment]
Hi Cindy, Thanks for reporting. Yes, kipoi-veff has been replaced by kipoi-veff2. Unlike kipoi-veff kipoi-veff2 does not depend on 'postprocessing' field of model.yaml to infer  compatibility with variant effect prediction. Thats why they were removed. 

Since you are short on time, I have added the postprocessing parts back for DeepSEA models. They should now be compatible with kipoi-veff.

An ideal solution would be to force kipoi-veff to use an earlier version of this mdoels repository. I dont see any straight forward way of achieving that. I will look for a solution.

Can you try out once more please? Let me know how it goes.
